spring:
  application:
    name: ${SPRING_APPLICATION_NAME:spring-app}
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:testdb}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:password}

github:
  token: ${AUTHORIZATION_TOKEN}

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_INCLUDE_ENDPOINT:*}
    endpoint:
      health:
        show-details: ${SHOW_DETAILS:always}